/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpellsRouteImport } from './routes/spells'
import { Route as CreateCharacterRouteImport } from './routes/create-character'
import { Route as IndexRouteImport } from './routes/index'

const SpellsRoute = SpellsRouteImport.update({
  id: '/spells',
  path: '/spells',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCharacterRoute = CreateCharacterRouteImport.update({
  id: '/create-character',
  path: '/create-character',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-character': typeof CreateCharacterRoute
  '/spells': typeof SpellsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-character': typeof CreateCharacterRoute
  '/spells': typeof SpellsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-character': typeof CreateCharacterRoute
  '/spells': typeof SpellsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-character' | '/spells'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-character' | '/spells'
  id: '__root__' | '/' | '/create-character' | '/spells'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateCharacterRoute: typeof CreateCharacterRoute
  SpellsRoute: typeof SpellsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spells': {
      id: '/spells'
      path: '/spells'
      fullPath: '/spells'
      preLoaderRoute: typeof SpellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-character': {
      id: '/create-character'
      path: '/create-character'
      fullPath: '/create-character'
      preLoaderRoute: typeof CreateCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateCharacterRoute: CreateCharacterRoute,
  SpellsRoute: SpellsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
