/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpellsImport } from './routes/spells'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SpellsRoute = SpellsImport.update({
  id: '/spells',
  path: '/spells',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/spells': {
      id: '/spells'
      path: '/spells'
      fullPath: '/spells'
      preLoaderRoute: typeof SpellsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spells': typeof SpellsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spells': typeof SpellsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/spells': typeof SpellsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spells'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spells'
  id: '__root__' | '/' | '/spells'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpellsRoute: typeof SpellsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpellsRoute: SpellsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/spells"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/spells": {
      "filePath": "spells.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
